/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_teamnhip4_minichat;


import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import org.codehaus.jackson.map.ObjectMapper;
/**
 *
 * @author T.Công
 */
public class MAIN_CHAT extends javax.swing.JFrame {

    /**
     * Creates new form MAIN_CHAT
     */
    public static String CURRENT_USER;
    final private DefaultListModel<String> friendListModel;
    final private HashMap<String,String> mapChatContent;
    public MAIN_CHAT() {
        friendListModel = new DefaultListModel<>();
        mapChatContent = new HashMap<>();
        initComponents();
        lstFriends.setModel(friendListModel);
        CURRENT_USER = DANGKY.USER_NAME;
        txtThongTinCaNhan.setText(CURRENT_USER);
        getAndDisplayUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNoiDungTroChuyen = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstFriends = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        txtThongTinCaNhan = new javax.swing.JTextField();
        btLogout = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btSend = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblReceiver = new javax.swing.JLabel();
        txtNhanTin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 238, 184));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("CHƯƠNG TRÌNH CHAT - TEAM NHỊP 4");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_teamnhip4_minichat/image/aaaaaa.png"))); // NOI18N
        jLabel2.setText("NỘI DUNG CUỘC TRÒ CHUYỆN");

        txtNoiDungTroChuyen.setColumns(20);
        txtNoiDungTroChuyen.setRows(5);
        jScrollPane1.setViewportView(txtNoiDungTroChuyen);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_teamnhip4_minichat/image/children.gif"))); // NOI18N
        jLabel3.setText("BẠN BÈ ĐANG ONLINE");

        lstFriends.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstFriendsMouseClicked(evt);
            }
        });
        lstFriends.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstFriendsValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstFriends);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_teamnhip4_minichat/image/whos_online.gif"))); // NOI18N
        jLabel4.setText("THÔNG TIN CÁ NHÂN");

        txtThongTinCaNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThongTinCaNhanActionPerformed(evt);
            }
        });

        btLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_teamnhip4_minichat/image/logout.png"))); // NOI18N
        btLogout.setText("Logout");
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_teamnhip4_minichat/image/mw.png"))); // NOI18N
        jLabel5.setText("MESSAGE");

        btSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_teamnhip4_minichat/image/send.png"))); // NOI18N
        btSend.setText("SEND");
        btSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSendActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_teamnhip4_minichat/image/receive.png"))); // NOI18N
        jButton3.setText("Receive");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblReceiver.setForeground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                                        .addComponent(lblReceiver, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNhanTin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtThongTinCaNhan))
                                    .addComponent(btLogout)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btSend)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lblReceiver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btLogout))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btSend)
                            .addComponent(jButton3)))
                    .addComponent(txtNhanTin))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
      
    private void txtThongTinCaNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThongTinCaNhanActionPerformed
        // TODO add your handling code here:
       // DANGKY lg = new DANGKY();
       // if(lg.equals(lg)== true)
      //  {
      //      String a = "Xin chào teamnhip4";
       //     txtThongTinCaNhan.add(a, lg);
       // }
    }//GEN-LAST:event_txtThongTinCaNhanActionPerformed

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        // TODO add your handling code here:
        DANGKY lg = new DANGKY();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btLogoutActionPerformed

    private void lstFriendsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstFriendsMouseClicked
        // TODO add your handling code here:
        //PRIVATE_CHAT prc = new PRIVATE_CHAT();
        //prc.setVisible(true);
        //prc.setResizable(false);
	//prc.setTitle("Chat riêng tư - Private Chat");
	//prc.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_lstFriendsMouseClicked

    private void btSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSendActionPerformed
        // TODO add your handling code here:
        
        String s = txtNhanTin.getText().toString();
        txtNhanTin.setToolTipText("Tooltip");
        txtNhanTin.setForeground(Color.RED);
        if (s.length() > 0){
            txtNoiDungTroChuyen.append(CURRENT_USER + ": " + s + "\n");
            txtNoiDungTroChuyen.setToolTipText("Tooltip");
        txtNoiDungTroChuyen.setForeground(Color.RED);
            txtNhanTin.setText("");
            try{
                MyMessage m = new MyMessage();
                m.sender = CURRENT_USER;
                m.receiver = lblReceiver.getText();
                m.type = "chat";
                m.content = s;
                client client = new client();
                MyMessage r = client.send(m);
                
                
                nhan();
                
                
            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btSendActionPerformed
public void nhan()
{
    try{
            MyMessage m = new MyMessage();
            m.sender = CURRENT_USER;
            m.receiver = "server";
            m.type = "getmessages";
            m.content = lblReceiver.getText();
            client client = new client();
            MyMessage r = client.send(m);
            System.out.println(r.content);
            ObjectMapper mapper = new ObjectMapper();
            ArrayList<String> b = mapper.readValue(r.content, ArrayList.class);
            for (String s:b){
                txtNoiDungTroChuyen.append(lblReceiver.getText() + ": " + s + "\n");
                lblReceiver.setToolTipText("");
                lblReceiver.setForeground(Color.BLUE);
                txtNoiDungTroChuyen.setToolTipText("");
                txtNoiDungTroChuyen.setForeground(Color.LIGHT_GRAY);
            }
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try{
            MyMessage m = new MyMessage();
            m.sender = CURRENT_USER;
            m.receiver = "server";
            m.type = "getmessages";
            m.content = lblReceiver.getText();
            client client = new client();
            MyMessage r = client.send(m);
            System.out.println(r.content);
            ObjectMapper mapper = new ObjectMapper();
            ArrayList<String> b = mapper.readValue(r.content, ArrayList.class);
            for (String s:b){
                txtNoiDungTroChuyen.append(lblReceiver.getText() + ": " + s + "\n");
            }
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void lstFriendsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstFriendsValueChanged
        // TODO add your handling code here:
        
         String s = lblReceiver.getText();
        String content = txtNoiDungTroChuyen.getText();
        mapChatContent.put(s, content);
        
        if (!evt.getValueIsAdjusting()){
            JList source = (JList)evt.getSource();
            String selected = source.getSelectedValue().toString();
            lblReceiver.setText(selected);
            content = mapChatContent.get(selected);
            txtNoiDungTroChuyen.setText(content);
        }
    }//GEN-LAST:event_lstFriendsValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAIN_CHAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAIN_CHAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAIN_CHAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAIN_CHAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MAIN_CHAT mc = new MAIN_CHAT();
                mc.setVisible(true);
                mc.setResizable(false);
	        mc.setTitle("Phần mềm Chat - TeamNhip4");
	        mc.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogout;
    private javax.swing.JButton btSend;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblReceiver;
    private javax.swing.JList<String> lstFriends;
    private javax.swing.JTextField txtNhanTin;
    private javax.swing.JTextArea txtNoiDungTroChuyen;
    private javax.swing.JTextField txtThongTinCaNhan;
    // End of variables declaration//GEN-END:variables

    private void getAndDisplayUser() {
         //To change body of generated methods, choose Tools | Templates.
          try{
           
            MyMessage m = new MyMessage();
            m.sender = CURRENT_USER;
            m.receiver = "server";
            m.type = "getusers";
            client client = new client();
            MyMessage r = client.send(m);
            ObjectMapper mapper = new ObjectMapper();
            ArrayList<String> b = mapper.readValue(r.content, ArrayList.class);
            for (int i=0; i<b.size(); i++){
                String s = b.get(i);
                friendListModel.addElement(s);
                mapChatContent.put(s, "");
                if (i==0){
                    lblReceiver.setText(s);     
                }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
}
